# R Markdown Notebook Generator for Code Visibility System
# Generate interactive R Markdown notebooks with analysis workflows
#
# Author: Prairie Genomics Team
# Date: January 27, 2025
# Purpose: Phase 3 - Enhanced Export Capabilities

# Load required libraries
if (!requireNamespace("rmarkdown", quietly = TRUE)) {
  cat("⚠️ Installing rmarkdown package...\n")
  install.packages("rmarkdown")
}

library(rmarkdown)

# Generate comprehensive R Markdown notebook
generate_rmarkdown_notebook <- function(session_id, output_file = NULL, 
                                       notebook_type = "analysis", 
                                       include_interactive = TRUE,
                                       code_folding = "show",
                                       theme = "default") {
  tryCatch({
    cat("📓 Generating R Markdown notebook...\n")
    
    # Load session data
    session_data <- get_session_data(session_id)
    if (is.null(session_data)) {
      stop("Session data not found for session: ", session_id)
    }
    
    # Create output filename if not provided
    if (is.null(output_file)) {
      timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
      output_file <- paste0("prairie_analysis_notebook_", session_id, "_", timestamp, ".Rmd")
    }
    
    cat("📝 Building notebook content...\n")
    
    # Create R Markdown content based on type
    rmd_content <- switch(notebook_type,
      "analysis" = create_analysis_notebook(session_data, include_interactive, code_folding, theme),
      "tutorial" = create_tutorial_notebook(session_data, include_interactive, code_folding, theme),
      "report" = create_report_notebook(session_data, include_interactive, code_folding, theme),
      "minimal" = create_minimal_notebook(session_data, include_interactive, code_folding, theme)
    )
    
    # Write notebook to file
    cat("💾 Writing notebook to file:", output_file, "\n")
    writeLines(rmd_content, output_file)
    
    # Generate notebook metadata
    notebook_info <- list(
      session_id = session_id,
      output_file = output_file,
      generated_at = Sys.time(),
      file_size = file.size(output_file),
      notebook_type = notebook_type,
      includes_interactive = include_interactive,
      code_folding = code_folding,
      theme = theme,
      chunks = count_code_chunks(rmd_content)
    )
    
    cat("✅ R Markdown notebook generated successfully!\n")
    cat("📋 Notebook details:\n")
    cat("   - File:", output_file, "\n")
    cat("   - Size:", round(notebook_info$file_size / 1024, 1), "KB\n")
    cat("   - Type:", notebook_type, "\n")
    cat("   - Code chunks:", notebook_info$chunks, "\n")
    cat("   - Interactive elements:", include_interactive, "\n")
    
    return(notebook_info)
    
  }, error = function(e) {
    cat("❌ R Markdown notebook generation failed:", e$message, "\n")
    return(NULL)
  })
}

# Create analysis-focused notebook
create_analysis_notebook <- function(session_data, include_interactive, code_folding, theme) {
  # YAML header
  yaml_header <- create_yaml_header("analysis", include_interactive, code_folding, theme, session_data)
  
  # Setup chunk
  setup_chunk <- create_setup_chunk(session_data, include_interactive)
  
  # Introduction
  intro_section <- paste0('
# Genomics Analysis Notebook

This R Markdown notebook reproduces the genomics analysis performed using the Prairie Genomics Suite v5 Enhanced platform.

## Analysis Overview

- **Session ID:** `', session_data$session_id, '`
- **Generated:** ', format(Sys.time(), "%Y-%m-%d %H:%M:%S"), '
- **Species:** ', session_data$species %||% "Not specified", '
- **Total Steps:** ', length(session_data$steps), '
- **Analysis Types:** ', paste(unique(sapply(session_data$steps, function(x) x$analysis_type)), collapse = ", "), '

## How to Use This Notebook

1. **Update file paths** in the data loading section to point to your data files
2. **Run chunks sequentially** by clicking the green "play" button in each chunk
3. **Modify parameters** as needed for your specific analysis
4. **Export results** using the provided export functions

---
')
  
  # Data loading section
  data_section <- create_data_loading_rmd_section(session_data)
  
  # Analysis steps sections
  analysis_sections <- create_analysis_rmd_sections(session_data, include_interactive)
  
  # Results and visualization section
  results_section <- create_results_rmd_section(session_data, include_interactive)
  
  # Export section
  export_section <- create_export_rmd_section(session_data)
  
  # Session info section
  session_info_section <- '
## Session Information

```{r session-info}
sessionInfo()
```

---

*This notebook was generated by the Prairie Genomics Suite v5 Enhanced platform.*
'
  
  # Combine all sections
  complete_rmd <- paste(
    yaml_header,
    setup_chunk,
    intro_section,
    data_section,
    analysis_sections,
    results_section,
    export_section,
    session_info_section,
    sep = "\n"
  )
  
  return(complete_rmd)
}

# Create tutorial-style notebook
create_tutorial_notebook <- function(session_data, include_interactive, code_folding, theme) {
  # YAML header for tutorial
  yaml_header <- create_yaml_header("tutorial", include_interactive, code_folding, theme, session_data)
  
  # Setup chunk
  setup_chunk <- create_setup_chunk(session_data, include_interactive, tutorial_mode = TRUE)
  
  # Tutorial introduction
  tutorial_intro <- '
# Genomics Analysis Tutorial

Welcome to this interactive genomics analysis tutorial! This notebook will guide you through a complete genomics analysis workflow step by step.

## Learning Objectives

By the end of this tutorial, you will be able to:

- Load and preprocess genomics data
- Perform differential expression analysis with DESeq2
- Conduct pathway enrichment analysis
- Create publication-quality visualizations
- Export and share your results

## Prerequisites

- Basic knowledge of R programming
- Understanding of genomics concepts
- Familiarity with RNA-seq data

---

## Tutorial Overview

This tutorial is based on an actual analysis performed in the Prairie Genomics Suite. We\'ll walk through each step with detailed explanations and exercises.

'
  
  # Tutorial sections with explanations
  tutorial_sections <- create_tutorial_rmd_sections(session_data, include_interactive)
  
  # Exercises section
  exercises_section <- '
## Practice Exercises

Try these exercises to test your understanding:

### Exercise 1: Parameter Exploration
Modify the analysis parameters and observe how the results change.

```{r exercise-1, eval=FALSE}
# Try different significance thresholds
# padj_cutoff <- 0.01  # More stringent
# fc_cutoff <- 2       # Larger fold change requirement

# Re-run the analysis with new parameters
```

### Exercise 2: Visualization Customization
Create your own custom visualizations.

```{r exercise-2, eval=FALSE}
# Create a custom volcano plot with different colors
# Add your code here
```

### Exercise 3: Additional Analysis
Explore other pathway databases or analysis methods.

```{r exercise-3, eval=FALSE}
# Try different pathway databases (Reactome, WikiPathways)
# Add your exploration code here
```

---
'
  
  # Combine tutorial sections
  complete_tutorial <- paste(
    yaml_header,
    setup_chunk,
    tutorial_intro,
    tutorial_sections,
    exercises_section,
    '
## Next Steps

Congratulations! You\'ve completed the genomics analysis tutorial. Here are some suggestions for further learning:

- Explore additional pathway databases
- Try different visualization techniques  
- Apply these methods to your own data
- Read the referenced papers for deeper understanding

---

*Tutorial generated by Prairie Genomics Suite v5 Enhanced*
',
    sep = "\n"
  )
  
  return(complete_tutorial)
}

# Create report-style notebook
create_report_notebook <- function(session_data, include_interactive, code_folding, theme) {
  yaml_header <- create_yaml_header("report", include_interactive, code_folding, theme, session_data)
  
  # Report content focuses on results presentation
  report_content <- paste0('
# Genomics Analysis Report

## Executive Summary

This report presents the results of a comprehensive genomics analysis performed on ', format(session_data$start_time, "%Y-%m-%d"), '. The analysis identified significant biological patterns and pathway enrichments using established bioinformatics methods.

### Key Findings

- **Total genes analyzed:** [To be filled from data]
- **Significant differentially expressed genes:** [To be calculated]
- **Enriched biological pathways:** [To be determined]
- **Statistical significance threshold:** p < 0.05 (FDR corrected)

')
  
  # Add condensed analysis sections focused on results
  condensed_sections <- create_condensed_rmd_sections(session_data, include_interactive)
  
  complete_report <- paste(
    yaml_header,
    create_setup_chunk(session_data, include_interactive, report_mode = TRUE),
    report_content,
    condensed_sections,
    '
## Conclusions

The genomics analysis successfully identified biologically relevant patterns. These results provide a foundation for further experimental validation and hypothesis generation.

## Methods Summary

All analyses were performed using established bioinformatics methods with appropriate statistical corrections. The complete analysis workflow is reproducible using the code provided in this report.

---

*Report generated by Prairie Genomics Suite v5 Enhanced on ', format(Sys.time(), "%Y-%m-%d"), '*
',
    sep = "\n"
  )
  
  return(complete_report)
}

# Create minimal notebook
create_minimal_notebook <- function(session_data, include_interactive, code_folding, theme) {
  yaml_header <- '---
title: "Genomics Analysis - Quick Reference"
output:
  html_notebook:
    code_folding: hide
    toc: true
    toc_float: true
---'
  
  # Minimal content with just essential code
  minimal_content <- paste0(
    yaml_header, '\n\n',
    create_setup_chunk(session_data, FALSE, minimal_mode = TRUE),
    '
# Quick Analysis Reference

This notebook contains the essential code for reproducing the genomics analysis.

## Data Loading

```{r data-loading}
# Update file paths as needed
expression_file <- "path/to/expression_data.csv"
annotation_file <- "path/to/sample_annotation.csv"

# Load data (uncomment when ready)
# expression_data <- read.csv(expression_file, row.names = 1)
# sample_annotation <- read.csv(annotation_file, row.names = 1)
```

## Analysis Steps

',
    create_minimal_rmd_sections(session_data),
    '
## Export Results

```{r export}
# Export results (uncomment when ready)
# write.csv(results, "analysis_results.csv")
```
'
  )
  
  return(minimal_content)
}

# Create YAML header based on notebook type
create_yaml_header <- function(type, include_interactive, code_folding, theme, session_data) {
  base_title <- switch(type,
    "analysis" = "Genomics Analysis Notebook",
    "tutorial" = "Genomics Analysis Tutorial", 
    "report" = "Genomics Analysis Report",
    "minimal" = "Genomics Analysis - Quick Reference"
  )
  
  output_format <- if (include_interactive) {
    paste0('  html_notebook:
    code_folding: ', code_folding, '
    toc: true
    toc_float: true
    theme: ', theme, '
    highlight: tango
    df_print: paged')
  } else {
    paste0('  html_document:
    code_folding: ', code_folding, '
    toc: true
    toc_float: true
    theme: ', theme, '
    highlight: tango')
  }
  
  yaml <- paste0('---
title: "', base_title, '"
subtitle: "Generated by Prairie Genomics Suite v5 Enhanced"
author: "Prairie Genomics Analysis"
date: "`r format(Sys.time(), \'%B %d, %Y\')`"
output:
', output_format, '
---')
  
  return(yaml)
}

# Create setup chunk
create_setup_chunk <- function(session_data, include_interactive, tutorial_mode = FALSE, 
                              report_mode = FALSE, minimal_mode = FALSE) {
  
  chunk_options <- if (minimal_mode) {
    'echo=FALSE, message=FALSE, warning=FALSE'
  } else if (report_mode) {
    'echo=FALSE, message=FALSE, warning=FALSE, results="hide"'
  } else {
    'message=FALSE, warning=FALSE'
  }
  
  packages <- extract_required_packages(session_data)
  
  setup_content <- paste0('
```{r setup, include=FALSE}
knitr::opts_chunk$set(', chunk_options, ')

# Load required packages
packages <- c("', paste(packages, collapse = '", "'), '")

for (pkg in packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    if (pkg %in% c("DESeq2", "clusterProfiler", "org.Hs.eg.db", "org.Mm.eg.db")) {
      if (!requireNamespace("BiocManager", quietly = TRUE)) {
        install.packages("BiocManager")
      }
      BiocManager::install(pkg, update = FALSE, ask = FALSE)
    } else {
      install.packages(pkg)
    }
  }
  library(pkg, character.only = TRUE)
}

# Set global options
options(stringsAsFactors = FALSE)
set.seed(42)
```
')
  
  if (tutorial_mode) {
    setup_content <- paste0(setup_content, '

```{r tutorial-setup}
# Tutorial-specific setup
cat("🎓 Welcome to the Genomics Analysis Tutorial!\\n")
cat("📚 This notebook will guide you through each step\\n")
cat("💡 Look for tutorial tips marked with this icon\\n")
```
')
  }
  
  return(setup_content)
}

# Create data loading section for R Markdown
create_data_loading_rmd_section <- function(session_data) {
  '
## Data Loading

First, we need to load our genomics data. Update the file paths below to match your data location.

```{r data-setup}
# File paths - UPDATE THESE TO MATCH YOUR DATA
expression_file <- "path/to/your/expression_data.csv"
annotation_file <- "path/to/your/sample_annotation.csv"

cat("📂 Data Loading Instructions\\n")
cat("=============================\\n")
cat("Please update the file paths above to point to your data files.\\n")
cat("Then uncomment and run the loading commands below.\\n\\n")
```

```{r data-loading, eval=FALSE}
# Load expression data (uncomment when file paths are updated)
# expression_data <- read.csv(expression_file, row.names = 1, check.names = FALSE)
# cat("✅ Loaded expression data:", nrow(expression_data), "genes x", ncol(expression_data), "samples\\n")

# Load sample annotation (uncomment when file paths are updated)  
# sample_annotation <- read.csv(annotation_file, row.names = 1, check.names = FALSE)
# cat("✅ Loaded sample annotation:", nrow(sample_annotation), "samples\\n")

# Verify sample names match
# cat("Sample name check:\\n")
# cat("Expression samples:", head(colnames(expression_data)), "\\n")
# cat("Annotation samples:", head(rownames(sample_annotation)), "\\n")
```

'
}

# Create analysis sections for R Markdown
create_analysis_rmd_sections <- function(session_data, include_interactive) {
  sections <- ""
  
  for (i in seq_along(session_data$steps)) {
    step <- session_data$steps[[i]]
    
    sections <- paste0(sections, '
## Step ', i, ': ', step$step_name, '

', step$description %||% "This step performs a key part of the genomics analysis.", '

```{r step-', i, ', eval=FALSE}
# ', step$step_name, '
', step$r_code %||% paste("# Code for", step$step_name), '
```

')
    
    if (!is.null(step$output_summary)) {
      sections <- paste0(sections, '
**Results Summary:** ', step$output_summary, '

')
    }
  }
  
  return(sections)
}

# Create tutorial sections with explanations
create_tutorial_rmd_sections <- function(session_data, include_interactive) {
  sections <- ""
  
  for (i in seq_along(session_data$steps)) {
    step <- session_data$steps[[i]]
    
    # Add tutorial explanation based on analysis type
    explanation <- switch(step$analysis_type,
      "DESeq2" = "💡 **Tutorial Tip:** DESeq2 is the gold standard for differential expression analysis. It uses negative binomial modeling to account for count data characteristics.",
      "GO" = "💡 **Tutorial Tip:** Gene Ontology enrichment helps us understand the biological processes affected by our differentially expressed genes.",
      "KEGG" = "💡 **Tutorial Tip:** KEGG pathway analysis reveals which metabolic and signaling pathways are enriched in our gene set.",
      "GSEA" = "💡 **Tutorial Tip:** Gene Set Enrichment Analysis considers all genes ranked by expression change, not just significant ones.",
      "💡 **Tutorial Tip:** This analysis step contributes important information to our overall understanding."
    )
    
    sections <- paste0(sections, '
## Tutorial Step ', i, ': ', step$step_name, '

', explanation, '

### What This Step Does

', step$description %||% "This step performs an important part of the genomics analysis workflow.", '

### Code Explanation

```{r tutorial-step-', i, ', eval=FALSE}
# ', step$step_name, ' - Detailed walkthrough
', step$r_code %||% paste("# Code for", step$step_name), '
```

### Try It Yourself

Run the code above and observe the output. What patterns do you notice?

')
  }
  
  return(sections)
}

# Create condensed sections for reports
create_condensed_rmd_sections <- function(session_data, include_interactive) {
  sections <- '
## Analysis Results

'
  
  # Group similar analysis types
  analysis_types <- unique(sapply(session_data$steps, function(x) x$analysis_type))
  
  for (type in analysis_types) {
    type_steps <- session_data$steps[sapply(session_data$steps, function(x) x$analysis_type == type)]
    
    sections <- paste0(sections, '
### ', type, ' Analysis

```{r ', tolower(type), '-analysis, echo=FALSE}
# ', type, ' analysis results
', paste(sapply(type_steps, function(x) x$r_code %||% ""), collapse = "\n"), '
```

')
  }
  
  return(sections)
}

# Create minimal sections
create_minimal_rmd_sections <- function(session_data) {
  sections <- ""
  
  for (i in seq_along(session_data$steps)) {
    step <- session_data$steps[[i]]
    
    sections <- paste0(sections, '
```{r step-', i, '}
# ', step$step_name, '
', step$r_code %||% paste("# Code for", step$step_name), '
```

')
  }
  
  return(sections)
}

# Create results section
create_results_rmd_section <- function(session_data, include_interactive) {
  '
## Results and Visualizations

This section contains the key results and visualizations from your analysis.

```{r results-summary}
# Summary of analysis results
cat("📊 Analysis Summary\\n")
cat("==================\\n")
if (exists("deseq2_results")) {
  sig_genes <- sum(deseq2_results$padj < 0.05, na.rm = TRUE)
  cat("Significant genes found:", sig_genes, "\\n")
}
if (exists("go_results")) {
  cat("GO terms enriched:", nrow(go_results), "\\n")
}
if (exists("kegg_results")) {
  cat("KEGG pathways enriched:", nrow(kegg_results), "\\n")
}
```

### Key Visualizations

```{r volcano-plot, eval=FALSE}
# Create volcano plot (uncomment when data is loaded)
# if (exists("deseq2_results")) {
#   volcano_plot <- create_volcano_plot(deseq2_results)
#   print(volcano_plot)
# }
```

```{r pathway-plots, eval=FALSE}
# Create pathway visualizations (uncomment when data is available)
# if (exists("go_results") && nrow(go_results) > 0) {
#   # Add pathway visualization code
# }
```

'
}

# Create export section
create_export_rmd_section <- function(session_data) {
  '
## Export Results

Use this section to export your analysis results in various formats.

```{r export-setup}
# Create output directory
output_dir <- "analysis_results"
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
  cat("📁 Created output directory:", output_dir, "\\n")
}
```

```{r export-results, eval=FALSE}
# Export DESeq2 results (uncomment when data is available)
# if (exists("deseq2_results")) {
#   write.csv(deseq2_results, file.path(output_dir, "deseq2_results.csv"))
#   cat("✅ Exported DESeq2 results\\n")
# }

# Export pathway results (uncomment when data is available)
# if (exists("go_results")) {
#   write.csv(go_results, file.path(output_dir, "go_results.csv"), row.names = FALSE)
#   cat("✅ Exported GO results\\n")
# }

# if (exists("kegg_results")) {
#   write.csv(kegg_results, file.path(output_dir, "kegg_results.csv"), row.names = FALSE)
#   cat("✅ Exported KEGG results\\n")
# }
```

```{r export-plots, eval=FALSE}
# Export plots (uncomment when plots are created)
# if (exists("volcano_plot")) {
#   ggsave(file.path(output_dir, "volcano_plot.png"), volcano_plot, 
#          width = 8, height = 6, dpi = 300)
#   cat("✅ Exported volcano plot\\n")
# }
```

'
}

# Count code chunks in R Markdown content
count_code_chunks <- function(rmd_content) {
  chunk_pattern <- "```\\{r"
  length(gregexpr(chunk_pattern, paste(rmd_content, collapse = "\n"))[[1]])
}

# Generate multiple notebook formats
generate_notebook_suite <- function(session_id, output_dir = "notebooks") {
  tryCatch({
    cat("📚 Generating complete notebook suite...\n")
    
    # Create output directory
    if (!dir.exists(output_dir)) {
      dir.create(output_dir, recursive = TRUE)
    }
    
    notebooks_generated <- list()
    
    # Generate different notebook types
    notebook_types <- c("analysis", "tutorial", "report", "minimal")
    
    for (type in notebook_types) {
      cat("📓 Generating", type, "notebook...\n")
      
      notebook_file <- file.path(output_dir, paste0("prairie_", type, "_notebook_", 
                                                   format(Sys.time(), "%Y%m%d_%H%M%S"), ".Rmd"))
      
      notebook_info <- generate_rmarkdown_notebook(
        session_id = session_id,
        output_file = notebook_file,
        notebook_type = type,
        include_interactive = TRUE,
        code_folding = if (type == "tutorial") "hide" else "show"
      )
      
      notebooks_generated[[type]] <- notebook_info
    }
    
    suite_info <- list(
      session_id = session_id,
      output_dir = output_dir,
      generated_at = Sys.time(),
      notebooks = notebooks_generated,
      total_notebooks = length(notebooks_generated)
    )
    
    cat("✅ Notebook suite generated successfully!\n")
    cat("📋 Suite summary:\n")
    cat("   - Output directory:", output_dir, "\n")
    cat("   - Total notebooks:", suite_info$total_notebooks, "\n")
    cat("   - Types:", paste(names(notebooks_generated), collapse = ", "), "\n")
    
    return(suite_info)
    
  }, error = function(e) {
    cat("❌ Notebook suite generation failed:", e$message, "\n")
    return(NULL)
  })
}

cat("✅ R Markdown Notebook Generator loaded successfully!\n")
cat("📋 Available functions:\n")
cat("   - generate_rmarkdown_notebook(): Create R Markdown notebooks\n")
cat("   - generate_notebook_suite(): Create multiple notebook types\n")
cat("   - Types: 'analysis', 'tutorial', 'report', 'minimal'\n")
cat("   - Features: Interactive elements, code folding, tutorials\n")
cat("🎯 Ready for Phase 3 R Markdown generation!\n")